// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSr3oifB1YmZOYZ-cmEzZizMOB6HBXaMU',
    appId: '1:937544576882:web:b0dd4c22cf493a271df7eb',
    messagingSenderId: '937544576882',
    projectId: 'audiomood-55233',
    authDomain: 'audiomood-55233.firebaseapp.com',
    storageBucket: 'audiomood-55233.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPpUzlM5ZELc47WJQoP2A0EBn_Pp-Xsg',
    appId: '1:937544576882:android:b1369d60885ee3a11df7eb',
    messagingSenderId: '937544576882',
    projectId: 'audiomood-55233',
    storageBucket: 'audiomood-55233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfNEUpG3wkJNJAZpsz6B4MHRIDO37BVwk',
    appId: '1:937544576882:ios:5e1ddd0159d31e011df7eb',
    messagingSenderId: '937544576882',
    projectId: 'audiomood-55233',
    storageBucket: 'audiomood-55233.firebasestorage.app',
    iosClientId: '937544576882-959k7g735jkvcbfv0fot7thrjc28dgvq.apps.googleusercontent.com',
    iosBundleId: 'com.audiomood.audiomood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfNEUpG3wkJNJAZpsz6B4MHRIDO37BVwk',
    appId: '1:937544576882:ios:5e1ddd0159d31e011df7eb',
    messagingSenderId: '937544576882',
    projectId: 'audiomood-55233',
    storageBucket: 'audiomood-55233.firebasestorage.app',
    iosClientId: '937544576882-959k7g735jkvcbfv0fot7thrjc28dgvq.apps.googleusercontent.com',
    iosBundleId: 'com.audiomood.audiomood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSr3oifB1YmZOYZ-cmEzZizMOB6HBXaMU',
    appId: '1:937544576882:web:17be19477c9de3a51df7eb',
    messagingSenderId: '937544576882',
    projectId: 'audiomood-55233',
    authDomain: 'audiomood-55233.firebaseapp.com',
    storageBucket: 'audiomood-55233.firebasestorage.app',
  );
}
